#pragma once
#include "TryCatch.h"
#include "template_exec.h"
#include "lambda.h"
#include "bind_example.h"
#include "function.h"
#include "BaseStl.h"
#include "Signals2.h"
#include "genernal_example.h"